"""users table

Revision ID: 927068607aca
Revises: 72df0ee04f74
Create Date: 2018-02-28 17:30:53.376076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927068607aca'
down_revision = '72df0ee04f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('guid', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('subtype', sa.String(length=30), nullable=True),
    sa.Column('owner_guid', sa.Integer(), nullable=True),
    sa.Column('circle_guid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entity.guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=260), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entity.guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('body', sa.String(length=260), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entity.guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('code', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('language', sa.String(length=64), nullable=False))
    op.add_column('user', sa.Column('last_action', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=False))
    op.add_column('user', sa.Column('prev_last_action', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('prev_last_login', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['name'])
    op.create_foreign_key(None, 'user', 'entity', ['id'], ['guid'])
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_column('user', 'prev_last_login')
    op.drop_column('user', 'prev_last_action')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'last_action')
    op.drop_column('user', 'language')
    op.drop_column('user', 'code')
    op.drop_table('object')
    op.drop_table('circle')
    op.drop_table('channel')
    op.drop_table('entity')
    # ### end Alembic commands ###
